### ISSUE TITLE
HTTP Error 308?

### ISSUE THREAD

**Issue by garymh** [pionl/bitbar-gitlab-ci#1]
Hi @pionl ! Not sure if you still use this or not, but I was trying it out and I keep getting a 308 error...

**Comment by pionl** [comment]
I use it daily :) Can u create a list with your configuration ? (please remove tokens :) )

It seems that your gitlab forces redirect that the python script is not following.

**Comment by pionl** [comment]
I've checked that `urlopen` is not following redirect, just update your url.

**Comment by garymh** [comment]
Ah! Updating it to `gitlab.com` instead of `www.gitlab.com` worked 😄 Thanks!
