### ISSUE TITLE
this plugin is featured on xbar' GitLab page but its outdated there

### ISSUE THREAD

**Issue by Grawl** [pionl/bitbar-gitlab-ci#5]
this is the page where this plugin is featured on xbar website: https://xbarapp.com/docs/plugins/Dev/Gitlab.html

this is the page where this plugin is located on xbar website: https://xbarapp.com/docs/plugins/Dev/Gitlab/gitlab_ci.1m.py.html

**Comment by pionl** [comment]
Thank you @Grawl - here is an PR https://github.com/matryer/xbar-plugins/pull/1768
